# Generated by Django 4.1.6 on 2023-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindingsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=100, unique=True)),
                ('definition_id', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('scans', models.ManyToManyField(to='findings.scan')),
            ],
        ),
    ]
