# Generated by Django 4.1.6 on 2023-02-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scan',
            new_name='ScanModel',
        ),
    ]
